In [1]:
import sklearn

In [2]:
sklearn.__version__

'0.24.2'

In [3]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd

In [4]:
iris = load_iris()

In [6]:
type(iris)

sklearn.utils.Bunch

In [10]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [11]:
iris['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [13]:
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [15]:
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [16]:
iris_df = pd.DataFrame(data=iris.data,columns=iris.feature_names)
iris_df.head(2)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2

In [17]:
iris_df['label']=iris.target

In [18]:
iris_df.sample(2)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
92                5.8               2.6                4.0               1.2   
74                6.4               2.9                4.3               1.3   

    label  
92      1  
74      1

In [25]:
X_train,X_test,y_train,y_test = train_test_split(iris.data,
                                                 iris.target,
                                                 test_size=0.2,
                                                 random_state=11)

In [20]:
X_train.shape,X_test.shape

((120, 4), (30, 4))

In [22]:
X_test,y_test

(array([[6.8, 3. , 5.5, 2.1],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.8, 5.1, 1.5],
        [6.3, 3.3, 4.7, 1.6],
        [6.4, 2.7, 5.3, 1.9],
        [4.9, 3.1, 1.5, 0.1],
        [6.7, 3.1, 4.4, 1.4],
        [5.7, 4.4, 1.5, 0.4],
        [4.8, 3.1, 1.6, 0.2],
        [6.1, 2.9, 4.7, 1.4],
        [6. , 2.2, 5. , 1.5],
        [6. , 2.2, 4. , 1. ],
        [5.4, 3. , 4.5, 1.5],
        [5.7, 2.5, 5. , 2. ],
        [6.9, 3.1, 5.4, 2.1],
        [4.5, 2.3, 1.3, 0.3],
        [6.3, 2.9, 5.6, 1.8],
        [5.6, 3. , 4.5, 1.5],
        [6.5, 3.2, 5.1, 2. ],
        [5.8, 2.7, 5.1, 1.9],
        [5.6, 2.5, 3.9, 1.1],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.6, 1. , 0.2],
        [6.4, 3.2, 4.5, 1.5],
        [4.8, 3. , 1.4, 0.1],
        [4.8, 3.4, 1.6, 0.2],
        [5.9, 3. , 5.1, 1.8],
        [6.6, 3. , 4.4, 1.4],
        [5.4, 3.9, 1.3, 0.4],
        [6. , 3.4, 4.5, 1.6]]),
 array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
        0, 1, 0, 0, 2, 1

In [26]:
dt_clf = DecisionTreeClassifier(random_state=11)

In [27]:
dt_clf.fit(X_train,y_train)

DecisionTreeClassifier(random_state=11)

In [28]:
pred = dt_clf.predict(X_test)

In [29]:
from sklearn.metrics import accuracy_score

In [31]:
accuracy_score(y_test,pred)*100

93.33333333333333

In [32]:
# 데이터 분리 없이 

In [33]:
iris = load_iris()
dt_clf = DecisionTreeClassifier()
train_data = iris.data
train_label = iris.target
dt_clf.fit(train_data,train_label)

DecisionTreeClassifier()

In [34]:
pred = dt_clf.predict(train_data)

In [35]:
accuracy_score(train_label,pred)

1.0

### k폴드

![](./img/k폴드.png)

In [36]:
from sklearn.model_selection import KFold
import numpy as np

In [37]:
iris = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

In [37]:
kfold = KFold(n_splits=5,shuffle=True)
cv_accuracy=[]

In [37]:
n_iter = 0
for train_index,test_index in kfold.split(iris.data):
    # print(train_index,test_index)
    X_train,X_test = iris.data[train_index],iris.data[test_index]
    y_train,y_test = iris.target[train_index],iris.target[test_index]
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print(f'\n{n_iter} 교차검증정확도: {accuracy},학습데이터크기:{train_size},검증데이터크기:{test_size}')
    print(f'{n_iter} 검증데이터 인덱스: {test_index}')
    cv_accuracy.append(accuracy)

In [47]:
np.mean(cv_accuracy)

0.9533400000000001

In [49]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

In [50]:
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [51]:
from sklearn.model_selection import StratifiedKFold

In [53]:
skf = StratifiedKFold(n_splits=3)
n_iter=0
for train_index,test_index in skf.split(iris_df,iris_df['label']):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print(n_iter)
    print('학습\n',label_train.value_counts())
    print('검증\n',label_test.value_counts())
    print('-'*20)

1
학습
 2    34
0    33
1    33
Name: label, dtype: int64
검증
 0    17
1    17
2    16
Name: label, dtype: int64
--------------------
2
학습
 1    34
0    33
2    33
Name: label, dtype: int64
검증
 0    17
2    17
1    16
Name: label, dtype: int64
--------------------
3
학습
 0    34
1    33
2    33
Name: label, dtype: int64
검증
 1    17
2    17
0    16
Name: label, dtype: int64
--------------------


In [55]:
iris = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

skfold = StratifiedKFold(n_splits=3,shuffle=True)
cv_accuracy=[]
n_iter = 0
for train_index,test_index in skfold.split(iris.data,iris.target):
    # print(train_index,test_index)
    X_train,X_test = iris.data[train_index],iris.data[test_index]
    y_train,y_test = iris.target[train_index],iris.target[test_index]
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print(f'\n{n_iter} 교차검증정확도: {accuracy},학습데이터크기:{train_size},검증데이터크기:{test_size}')
    print(f'{n_iter} 검증데이터 인덱스: {test_index}')
    cv_accuracy.append(accuracy)


1 교차검증정확도: 0.94,학습데이터크기:100,검증데이터크기:50
1 검증데이터 인덱스: [  4   5   7  19  21  22  26  28  29  30  31  33  34  38  39  45  47  55
  56  57  58  63  64  68  73  79  80  83  88  91  93  94  97  98 106 108
 116 117 120 121 123 125 127 130 132 133 135 137 139 148]

2 교차검증정확도: 0.98,학습데이터크기:100,검증데이터크기:50
2 검증데이터 인덱스: [  0   1   2   6   8  13  15  16  18  23  24  25  27  35  40  42  48  51
  53  59  61  66  69  70  71  74  75  82  84  86  95  96  99 103 104 105
 111 113 122 124 128 134 136 138 140 141 142 145 146 149]

3 교차검증정확도: 0.92,학습데이터크기:100,검증데이터크기:50
3 검증데이터 인덱스: [  3   9  10  11  12  14  17  20  32  36  37  41  43  44  46  49  50  52
  54  60  62  65  67  72  76  77  78  81  85  87  89  90  92 100 101 102
 107 109 110 112 114 115 118 119 126 129 131 143 144 147]


In [56]:
from sklearn.model_selection import cross_val_score

In [57]:
iris = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

In [60]:
cross_val_score(dt_clf,iris.data,iris.target,scoring='accuracy',cv=3)

array([0.98, 0.94, 0.98])

In [62]:
grid_parameters = { 'max_depth':[1,2,3],
                    'min_samples_split':[2,3]}

In [63]:
iris = load_iris()
X_train,X_test,y_train,y_test = train_test_split(iris.data,
                                                 iris.target,
                                                 test_size=0.2,
                                                 random_state=121)
dt_clf = DecisionTreeClassifier()

In [64]:
from sklearn.model_selection import GridSearchCV

In [65]:
grid_dtree = GridSearchCV(dt_clf,param_grid=grid_parameters,cv=3,refit=True)

In [66]:
grid_dtree.fit(X_train,y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]})

In [67]:
grid_dtree.cv_results_

{'mean_fit_time': array([0.00069205, 0.0005722 , 0.00057594, 0.00063467, 0.00033331,
        0.00061456]),
 'std_fit_time': array([0.00049034, 0.00045359, 0.0004228 , 0.00015079, 0.00047137,
        0.00043457]),
 'mean_score_time': array([0.        , 0.00016967, 0.0003341 , 0.00025733, 0.00066646,
        0.0003612 ]),
 'std_score_time': array([0.        , 0.00023996, 0.00047249, 0.00020518, 0.00047126,
        0.00051082]),
 'param_max_depth': masked_array(data=[1, 1, 2, 2, 3, 3],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_min_samples_split': masked_array(data=[2, 3, 2, 3, 2, 3],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'max_depth': 1, 'min_samples_split': 2},
  {'max_depth': 1, 'min_samples_split': 3},
  {'max_depth': 2, 'min_samples_split': 2},
  {'max_depth': 2, 'min_samples_split': 3},
  {'max_depth': 3, 'min_sample

In [68]:
grid_dtree.best_params_

{'max_depth': 3, 'min_samples_split': 2}

In [69]:
scoreds_df = pd.DataFrame(grid_dtree.cv_results_)
scoreds_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.000692      0.000490         0.000000        0.000000   
1       0.000572      0.000454         0.000170        0.000240   
2       0.000576      0.000423         0.000334        0.000472   
3       0.000635      0.000151         0.000257        0.000205   
4       0.000333      0.000471         0.000666        0.000471   
5       0.000615      0.000435         0.000361        0.000511   

  param_max_depth param_min_samples_split  \
0               1                       2   
1               1                       3   
2               2                       2   
3               2                       3   
4               3                       2   
5               3                       3   

                                     params  split0_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}              0.700   
1  {'max_depth': 1, 'min_samples_split': 3}              0.700   
2  {'max_depth': 2, 'min_samples_split': 2}              0.925   
3  {'max_depth': 2, 'min_samples_split': 3}              0.925   
4  {'max_depth': 3, 'min_samples_split': 2}              0.975   
5  {'max_depth': 3, 'min_samples_split': 3}              0.975   

   split1_test_score  split2_test_score  mean_test_score  std_test_score  \
0                0.7               0.70         0.700000    1.110223e-16   
1                0.7               0.70         0.700000    1.110223e-16   
2                1.0               0.95         0.958333    3.118048e-02   
3                1.0               0.95         0.958333    3.118048e-02   
4                1.0               0.95         0.975000    2.041241e-02   
5                1.0               0.95         0.975000    2.041241e-02   

   rank_test_score  
0                5  
1                5  
2                3  
3                3  
4                1  
5                1

In [70]:
scoreds_df.columns

Index(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_max_depth', 'param_min_samples_split', 'params',
       'split0_test_score', 'split1_test_score', 'split2_test_score',
       'mean_test_score', 'std_test_score', 'rank_test_score'],
      dtype='object')

In [71]:
scoreds_df[['params','mean_test_score','rank_test_score','split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

### 레이블 인코딩

In [72]:
from sklearn.preprocessing import LabelEncoder

In [74]:
items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [75]:
encoder.classes_

array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

In [77]:
encoder.inverse_transform([0,2,4,5])

ValueError: y contains previously unseen labels: [7]

In [78]:
from sklearn.preprocessing import OneHotEncoder

In [79]:
items

['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

In [82]:
encoder = LabelEncoder()
labels = encoder.fit_transform(items)
labels = labels.reshape(-1,1)

In [84]:
oh_encoder = OneHotEncoder()
oh_labels = oh_encoder.fit_transform(labels)

In [86]:
oh_labels.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [88]:
oh_labels.shape

(8, 6)

In [89]:
import pandas as pd

In [90]:
df = pd.DataFrame({'item':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})

In [91]:
df

item
0     TV
1    냉장고
2  전자레인지
3    컴퓨터
4    선풍기
5    선풍기
6     믹서
7     믹서

In [92]:
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

In [93]:
iris = load_iris()

In [94]:
iris_df = pd.DataFrame(data=iris.data,columns=iris.feature_names)

In [96]:
iris_df.mean()

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [97]:
iris_df.var()

sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [98]:
from sklearn.preprocessing import StandardScaler

In [99]:
scaler = StandardScaler()

In [100]:
iris_scaled = scaler.fit_transform(iris_df)

In [104]:
iris_df_scaled = pd.DataFrame(data= iris_scaled,columns=iris.feature_names)

In [105]:
iris_df_scaled.mean()

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

In [106]:
iris_df_scaled.var()

sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64

In [107]:
from sklearn.preprocessing import MinMaxScaler

In [108]:
scaler = MinMaxScaler()

In [109]:
iris_scaled = scaler.fit_transform(iris_df)

In [110]:
iris_df_scaled = pd.DataFrame(data= iris_scaled,columns=iris.feature_names)

In [111]:
iris_df.min(),iris_df.max()

(sepal length (cm)    4.3
 sepal width (cm)     2.0
 petal length (cm)    1.0
 petal width (cm)     0.1
 dtype: float64,
 sepal length (cm)    7.9
 sepal width (cm)     4.4
 petal length (cm)    6.9
 petal width (cm)     2.5
 dtype: float64)

In [112]:
iris_df_scaled.min(),iris_df_scaled.max()

(sepal length (cm)    0.0
 sepal width (cm)     0.0
 petal length (cm)    0.0
 petal width (cm)     0.0
 dtype: float64,
 sepal length (cm)    1.0
 sepal width (cm)     1.0
 petal length (cm)    1.0
 petal width (cm)     1.0
 dtype: float64)

In [113]:
train_array = np.arange(11).reshape(-1,1)
test_array = np.arange(6).reshape(-1,1)

In [114]:
train_array

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [115]:
test_array

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [116]:
scaler = MinMaxScaler()

In [117]:
scaler.fit(train_array)

MinMaxScaler()

In [118]:
scaler.transform(train_array)

array([[0. ],
       [0.1],
       [0.2],
       [0.3],
       [0.4],
       [0.5],
       [0.6],
       [0.7],
       [0.8],
       [0.9],
       [1. ]])

In [119]:
scaler.transform(test_array)

array([[0. ],
       [0.1],
       [0.2],
       [0.3],
       [0.4],
       [0.5]])

In [120]:
scaler.fit(test_array)

MinMaxScaler()

In [121]:
scaler.transform(test_array)

array([[0. ],
       [0.2],
       [0.4],
       [0.6],
       [0.8],
       [1. ]])